const persons = [
    {
        "name": "John Doe",
        "age": 30,
        "work": "chef",
        "mobile": "123-456-7890",
        "email": "john@example.com",
        "address": "123 Main St, City",
        "salary": 50000,
        "username": "john_doe",
        "password": "password123"
    },
    {
        "name": "Jane Smith",
        "age": 25,
        "work": "waiter",
        "mobile": "987-654-3210",
        "email": "jane@example.com",
        "address": "456 Oak St, Town",
        "salary": 40000,
        "username": "jane_smith",
        "password": "password456"
    },
    {
        "name": "Michael Johnson",
        "age": 35,
        "work": "manager",
        "mobile": "555-555-5555",
        "email": "michael@example.com",
        "address": "789 Elm St, Village",
        "salary": 60000,
        "username": "michael_johnson",
        "password": "password789"
    },
    {
        "name": "Emily Brown",
        "age": 28,
        "work": "chef",
        "mobile": "222-333-4444",
        "email": "emily@example.com",
        "salary": 55000,
        "username": "emily_brown",
        "password": "passwordabc"
    },
    "name": "Emma Taylor",
    "age": 22,
    "work": "waiter",
    "mobile": "666-777-8888",
    "email": "emma@example.com",
    "address": "987 Maple St, Borough",
    "salary": 38000,
    "username": "emma_taylor",
    "password": "password123"
},
{
    "name": "Daniel Anderson",
    "age": 32,
    "work": "manager",
    "mobile": "444-444-4444",
    "email": "daniel@example.com",
    "address": "654 Birch St, Hamlet",
    "salary": 65000,
    "username": "daniel_anderson",
    "password": "password456"
},